#!/bin/bash
#list of aliases compatible with bash/zsh
alias .='source'
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias vless='vim -u /usr/share/vim/vim71/macros/less.vim'
alias nyan='pygmentize -g'
alias dccanime='mv ~/.weechat/xfer/* ~/Downloads'
alias ramdir='mount -t tmpfs tmpfs /mnt -o size=1024m'
alias balls='cd $HOME/Dropbox/Stuff/Dropballs/ && python2 test1.py tingol && cd -'
alias trc='transmission-remote-cli'
alias els='els --els-icons=fontawesome'
alias v='f -e vim'
alias izbrisi='sudo pacman -Rs'
alias srb='setxkbmap rs latinyz'
alias eng='setxkbmap us'
alias gping='ping -c 3 www.google.com'
alias upg="packer -Syu"
alias htpc="ssh -p 2222 tingol@192.168.1.66"
alias deskss='scrot -cd 1 current.png && imgurup current.png | xclip -selection clipboard && notify-send "image uploaded successfully, address copied to buffer"'
alias tng='play -c 2 -n -c1 synth whitenoise lowpass -1 120 lowpass -1 120 lowpass -1 120 gain +10'
alias ocean='play -n -n --combine merge synth pinknoise band -n 1200 1800 tremolo 50 10 tremolo 0.14 70 tremolo 0.2 50'
alias magnet='aria2c --bt-metadata-only=true --bt-save-metadata=true'
alias xperiausb='mkdir xperia && jmtpfs ./xperia'
alias news='newsbeuter -q'
alias screenoff='xset dpms force standby'
alias speedtest='curl -o /dev/null http://speedtest.sea01.softlayer.com/downloads/test100.zip'
alias getsite='wget --recursive --page-requisites --convert-links --no-parent $1' 
alias record='script -ttiming recording'
alias replay='scriptreplay -ttiming recording'
