#!/bin/sh
xsetroot -cursor_name watch
command -v warpcursor && warpcursor 1
xset +fp /usr/share/fonts/local
xset fp rehash
xset r rate 250 50
xsetroot -solid black
xsetroot -cursor_name left_ptr
xmodmap .xmodmap &
xcape &
dropbox &
compton --backend glx --paint-on-overlay --vsync opengl-mswc &
dunst &
imlibsetroot -s f Dropbox/Photos/Walls/arch.png &
redshift -l 44:23 &
unclutter -idle 5 -noevents &
echo 240 | sudo tee /sys/devices/platform/i8042/serio1/sensitivity &
#barstatus | bar -d -f "DejaVu Sans Mono-9" &
exec frankenwm
