#!/bin/bash

DMENU="dmenu -h 28 -o 0.8 -dim 0.5 -y 350 -nb #1c2027 -nf #ffffff -sb #2980b9 -sf #ffffff -fn SourceCodePro-14:Medium"

choice=$(echo -e "jdred\nd2l\nbts\nbts2\nsheever\ndendi\ntpl\nsingsing\nxboct\nadmiralbulldog\nkolento\n" | $DMENU | cut -f 1)

case "$choice" in
    jdred) livestreamer -p mplayer twitch.tv/joindotared Medium ;;
    d2l) livestreamer -p mplayer twitch.tv/d2l Medium ;;
    bts) livestreamer -p mplayer twitch.tv/beyondthesummit Medium ;;
    bts2) livestreamer -p mplayer twitch.tv/beyondthesummit2 Medium ;;
    sheever) livestreamer -p mplayer twitch.tv/sheevergaming Medium ;;
    dendi) livestreamer -p mplayer twitch.tv/dendi Medium ;;
    singsing) livestreamer -p mplayer twitch.tv/sing_sing Medium ;;
    xboct) livestreamer -p mplayer twitch.tv/xboct Medium ;;
    admiralbulldog) livestreamer -p mplayer twitch.tv/admiralbulldog Medium ;;
    kolento) livestreamer  -p mplayer twitch.tv/kolento Medium ;;
esac
