#!/bin/sh

# upload images to imgur.com
# appends links and deletion links to the log
# depends: curl

# check if all args exist as files
for F in "$@"; do
    if ! test -f "$F"; then
        echo usage: $(basename $0) image ... && exit 1
    fi
done

LOG=$HOME/.imgurlog

# from http://imgur.com/tools/imgurbash.sh
APIKEY='b3625162d3418ac51a9ee805b1840452'

# upload all
for IMG in "$@"; do
    RESP=$(curl -F "image=@$IMG" -F "key=$APIKEY" \
        http://imgur.com/api/upload.xml 2> /dev/null)

    URL=$(echo $RESP | sed 's|.*<original_image>\(.*\)</original_image>.*|\1|')
    DELETEURL=$(echo $RESP | sed 's|.*<delete_page>\(.*\)</delete_page>.*|\1|')

    echo "$URL" >> $LOG
    echo "$DELETEURL" >> $LOG
    echo "$URL"
done
