#!/bin/sh
#monsterm invocation script

ff="/tmp/monsterm.fifo"
[[ -p $ff ]] || mkfifo -m 600 "$ff"

ds=('I' 'II' 'III' 'IV' 'V' )
ms=('T' 'M' 'B' 'G' 'F' )

while read -t 60 -r wmout || true; do
                unset music
                music=$(cmus-remote -Q | awk '$2 == "artist"{a=substr($0,12)} $2 == "title"{t=substr($0,11); exit} END{printf("%s - %s\n",a,t); exit(!t)}')
                tor=$(transmission-remote -l | egrep -v "Done|Sum" | wc -l)
        if [[ $wmout =~ ^(([[:digit:]]+:)+[[:digit:]]+ ?)+$ ]]; then
                unset r
                read -ra desktops <<< "$wmout"
                for desktop in "${desktops[@]}"; do
                        IFS=':' read -r d w m c u <<< "$desktop"
                        ((c)) && fg="1" bg="4" lc="\u1 " rc=" \ur" i="${ms[$m]}" || fg="8" bg="9" lc=" " rc=" "
                        ((w)) && ((! c)) && fg="4" lc="\ur " rc=" \ur"
                        ((u)) && fg="3" lc="\ur " rc=" \ur"
                        r+="\f$fg\b$bg$lc${ds[$d]}$rc\fr\br"
                done
            fi
                        printf "\\\l%s\\\r%s\n"  "$r \f1\b5 $i \f1\b2 $tor \r\f4\b0$music " "$(date "+\c\f2\b0 %I:%M") "
done < "$ff" | bar -f &

monsterwm > "$ff"
rm $ff

